version: 2
jobs:
  build:
    docker:
      - image: yarnpkg/dev
    steps:
      - checkout
      - run: 'yarn global add $(cat .circleci/packages.txt)'
      - run: 'pug-lint src/templates/*'
      - run: 'sass-lint src/scss/* -v -q --max-warnings=0'
